/* eslint-disable */
// This file is auto-generated by tools/generate-translations.mjs
// Do not edit manually. Update the source HTML and re-run the generator.

export type SupportedLocale = 'en' | 'ar';
export interface TranslationEntry { en: string; ar: string; }

export const translations: Record<string, TranslationEntry> = {
  "Home": {
    "en": "Home",
    "ar": "الرئيسية"
  },
  "Services": {
    "en": "Services",
    "ar": "الخدمات"
  },
  "Our Work": {
    "en": "Our Work",
    "ar": "أعمالنا"
  },
  "About": {
    "en": "About",
    "ar": "عن الشركة"
  },
  "Contact": {
    "en": "Contact",
    "ar": "اتصل بنا"
  },
  "Driven by Ideas. Designed for People.": {
    "en": "Driven by Ideas. Designed for People.",
    "ar": "مدفوع بالابتكار. مصمم للناس."
  },
  "Transforming businesses through innovative digital solutions, intelligent automation, and cutting-edge technology designed for the modern world": {
    "en": "Transforming businesses through innovative digital solutions, intelligent automation, and cutting-edge technology designed for the modern world",
    "ar": "نحول الأعمال من خلال الحلول الرقمية المبتكرة والأتمتة الذكية والتكنولوجيا المتطورة المصممة للعالم الحديث"
  },
  "Start Your Project": {
    "en": "Start Your Project",
    "ar": "ابدأ مشروعك"
  },
  "Learn More": {
    "en": "Learn More",
    "ar": "اعرف المزيد"
  },
  "Projects Delivered": {
    "en": "Projects Delivered",
    "ar": "مشروع منجز"
  },
  "Client Satisfaction": {
    "en": "Client Satisfaction",
    "ar": "رضا العملاء"
  },
  "Support": {
    "en": "Support",
    "ar": "الدعم"
  },
  "About Elenta Systems": {
    "en": "About Elenta Systems",
    "ar": "عن شركة إلنتا"
  },
  "Empowering Digital Transformation Across MENA": {
    "en": "Empowering Digital Transformation Across MENA",
    "ar": "تمكين التحول الرقمي عبر منطقة الشرق الأوسط وشمال أفريقيا"
  },
  "Since our founding, Elenta Systems has been at the forefront of digital innovation in Egypt and the broader MENA region. We specialize in creating scalable, efficient, and culturally-aware software solutions that drive business growth and operational excellence.": {
    "en": "Since our founding, Elenta Systems has been at the forefront of digital innovation in Egypt and the broader MENA region. We specialize in creating scalable, efficient, and culturally-aware software solutions that drive business growth and operational excellence.",
    "ar": "منذ تأسيسنا، تقود شركة إلنتا سيستمز مقدمة الابتكار الرقمي في مصر ومنطقة الشرق الأوسط وشمال أفريقيا الأوسع. نحن متخصصون في إنشاء حلول برمجية قابلة للتوسع وفعالة وواعية ثقافياً تحفز نمو الأعمال والتميز التشغيلي."
  },
  "Years Experience": {
    "en": "Years Experience",
    "ar": "سنوات الخبرة"
  },
  "Countries Served": {
    "en": "Countries Served",
    "ar": "دول مخدومة"
  },
  "Innovation-Driven": {
    "en": "Innovation-Driven",
    "ar": "مدفوع بالابتكار"
  },
  "Cutting-edge solutions for modern challenges": {
    "en": "Cutting-edge solutions for modern challenges",
    "ar": "حلول متطورة للتحديات الحديثة"
  },
  "Principles that power our partnerships": {
    "en": "Principles that power our partnerships",
    "ar": "المبادئ التي تعزز شراكاتنا"
  },
  "The principles that guide our work and define our commitment to excellence": {
    "en": "The principles that guide our work and define our commitment to excellence",
    "ar": "المبادئ التي توجه عملنا وتحدد التزامنا بالتميز"
  },
  "Mission": {
    "en": "Mission",
    "ar": "مهمتنا"
  },
  "Vision": {
    "en": "Vision",
    "ar": "رؤيتنا"
  },
  "Values": {
    "en": "Values",
    "ar": "قيمنا"
  },
  "Our Mission": {
    "en": "Our Mission",
    "ar": "مهمتنا"
  },
  "Empowering digital transformation across MENA": {
    "en": "Empowering digital transformation across MENA",
    "ar": "تمكين التحول الرقمي عبر منطقة الشرق الأوسط وشمال أفريقيا"
  },
  "To empower businesses across MENA with innovative digital solutions that drive growth, efficiency, and competitive advantage in the digital age.": {
    "en": "To empower businesses across MENA with innovative digital solutions that drive growth, efficiency, and competitive advantage in the digital age.",
    "ar": "تمكين الشركات عبر منطقة الشرق الأوسط وشمال أفريقيا بحلول رقمية مبتكرة تحفز النمو والكفاءة والميزة التنافسية في العصر الرقمي."
  },
  "Our Vision": {
    "en": "Our Vision",
    "ar": "رؤيتنا"
  },
  "Leading the region with human-centered innovation": {
    "en": "Leading the region with human-centered innovation",
    "ar": "ريادة المنطقة بابتكار محوره الإنسان"
  },
  "To be the leading digital transformation partner in the MENA region, recognized for our innovation, cultural sensitivity, and exceptional results.": {
    "en": "To be the leading digital transformation partner in the MENA region, recognized for our innovation, cultural sensitivity, and exceptional results.",
    "ar": "أن نكون الشريك الرائد للتحول الرقمي في منطقة الشرق الأوسط وشمال أفريقيا، معترف بنا لابتكارنا وحساسيتنا الثقافية ونتائجنا الاستثنائية."
  },
  "Our Values": {
    "en": "Our Values",
    "ar": "قيمنا"
  },
  "Relationships built on trust, integrity, and excellence": {
    "en": "Relationships built on trust, integrity, and excellence",
    "ar": "علاقات قائمة على الثقة والنزاهة والتميز"
  },
  "Innovation, Integrity, Excellence, and Client-centricity. We believe in building lasting relationships through trust, transparency, and delivering value beyond expectations.": {
    "en": "Innovation, Integrity, Excellence, and Client-centricity. We believe in building lasting relationships through trust, transparency, and delivering value beyond expectations.",
    "ar": "الابتكار والنزاهة والتميز والتركيز على العميل. نؤمن ببناء علاقات دائمة من خلال الثقة والشفافية وتقديم قيمة تفوق التوقعات."
  },
  "What We Do": {
    "en": "What We Do",
    "ar": "ما نقوم به"
  },
  "Comprehensive Digital Solutions": {
    "en": "Comprehensive Digital Solutions",
    "ar": "حلول رقمية شاملة"
  },
  "From ideation to implementation, we deliver end-to-end digital solutions that transform businesses and drive sustainable growth across diverse industries": {
    "en": "From ideation to implementation, we deliver end-to-end digital solutions that transform businesses and drive sustainable growth across diverse industries",
    "ar": "من الفكرة إلى التنفيذ، نقدم حلولاً رقمية شاملة تحول الأعمال وتحفز النمو المستدام عبر صناعات متنوعة"
  },
  "Scroll to explore": {
    "en": "Scroll to explore",
    "ar": "مرر للاستكشاف"
  },
  "Enterprise Solutions": {
    "en": "Enterprise Solutions",
    "ar": "حلول المؤسسات"
  },
  "Scalable ERP systems, CRM platforms, and business intelligence solutions that streamline operations and boost productivity across your organization.": {
    "en": "Scalable ERP systems, CRM platforms, and business intelligence solutions that streamline operations and boost productivity across your organization.",
    "ar": "أنظمة تخطيط الموارد المؤسسية قابلة للتوسع ومنصات إدارة علاقات العملاء وحلول ذكاء الأعمال التي تبسط العمليات وتعزز الإنتاجية."
  },
  "AI & Automation": {
    "en": "AI & Automation",
    "ar": "الذكاء الاصطناعي"
  },
  "Advanced AI solutions featuring Large Language Models (LLM), Retrieval-Augmented Generation (RAG), intelligent agents, and custom chatbots for enhanced business automation and customer engagement.": {
    "en": "Advanced AI solutions featuring Large Language Models (LLM), Retrieval-Augmented Generation (RAG), intelligent agents, and custom chatbots for enhanced business automation and customer engagement.",
    "ar": "حلول الذكاء الاصطناعي المتقدمة التي تتميز بنماذج اللغة الكبيرة (LLM) والتوليد المعزز بالاسترجاع (RAG) والوكلاء الذكيين وروبوتات الدردشة المخصصة لتعزيز أتمتة الأعمال وإشراك العملاء."
  },
  "Web & Mobile Development": {
    "en": "Web & Mobile Development",
    "ar": "تطوير الويب والهاتف"
  },
  "Full-stack development of responsive web applications and native mobile apps using cutting-edge frameworks and technologies.": {
    "en": "Full-stack development of responsive web applications and native mobile apps using cutting-edge frameworks and technologies.",
    "ar": "تطوير شامل لتطبيقات الويب التفاعلية وتطبيقات الهاتف المحمول الأصلية باستخدام أحدث الأطر والتقنيات."
  },
  "Cloud Solutions": {
    "en": "Cloud Solutions",
    "ar": "الحلول السحابية"
  },
  "Secure cloud migration, infrastructure management, and scalable cloud-native applications that grow with your business needs.": {
    "en": "Secure cloud migration, infrastructure management, and scalable cloud-native applications that grow with your business needs.",
    "ar": "هجرة سحابية آمنة وإدارة البنية التحتية وتطبيقات سحابية أصلية قابلة للتوسع تنمو مع احتياجات عملك."
  },
  "UX/UI Design": {
    "en": "UX/UI Design",
    "ar": "تصميم التجربة"
  },
  "User-centered design methodology creating intuitive interfaces that deliver exceptional user experiences and drive engagement.": {
    "en": "User-centered design methodology creating intuitive interfaces that deliver exceptional user experiences and drive engagement.",
    "ar": "منهجية تصميم محورها المستخدم لإنشاء واجهات بديهية تقدم تجارب مستخدم استثنائية وتزيد التفاعل."
  },
  "Digital Transformation": {
    "en": "Digital Transformation",
    "ar": "التحول الرقمي"
  },
  "Strategic consulting and implementation services to modernize your business processes and technology infrastructure for competitive advantage.": {
    "en": "Strategic consulting and implementation services to modernize your business processes and technology infrastructure for competitive advantage.",
    "ar": "خدمات استشارية وتنفيذية استراتيجية لتحديث عمليات عملك والبنية التحتية التكنولوجية للحصول على ميزة تنافسية."
  },
  "Our Portfolio": {
    "en": "Our Portfolio",
    "ar": "أعمالنا"
  },
  "Recent Projects & Success Stories": {
    "en": "Recent Projects & Success Stories",
    "ar": "المشاريع الأخيرة وقصص النجاح"
  },
  "Discover how we've helped businesses across various industries achieve their digital transformation goals with innovative solutions": {
    "en": "Discover how we've helped businesses across various industries achieve their digital transformation goals with innovative solutions",
    "ar": "اكتشف كيف ساعدنا الشركات عبر مختلف الصناعات في تحقيق أهداف التحول الرقمي بحلول مبتكرة"
  },
  "Vortex Robotics": {
    "en": "Vortex Robotics",
    "ar": "فورتكس روبوتيكس"
  },
  "Advanced robotics company website with cutting-edge design and seamless user experience for showcasing innovative robotic solutions.": {
    "en": "Advanced robotics company website with cutting-edge design and seamless user experience for showcasing innovative robotic solutions.",
    "ar": "موقع شركة الروبوتات المتقدمة بتصميم متطور وتجربة مستخدم سلسة لعرض الحلول الروبوتية المبتكرة."
  },
  "View Details": {
    "en": "View Details",
    "ar": "عرض التفاصيل"
  },
  "VeloOne Consulting": {
    "en": "VeloOne Consulting",
    "ar": "فيلوون للاستشارات"
  },
  "Professional consulting platform designed to connect businesses with expert consultants and streamline the consultation process.": {
    "en": "Professional consulting platform designed to connect businesses with expert consultants and streamline the consultation process.",
    "ar": "منصة استشارية مهنية مصممة لربط الشركات بالخبراء الاستشاريين وتبسيط عملية الاستشارة."
  },
  "HeartBeats Medical AI": {
    "en": "HeartBeats Medical AI",
    "ar": "هارت بيتس الطبي بالذكاء الاصطناعي"
  },
  "AI-powered medical platform for diabetic detection and patient management with comprehensive admin dashboard and doctor portal.": {
    "en": "AI-powered medical platform for diabetic detection and patient management with comprehensive admin dashboard and doctor portal.",
    "ar": "منصة طبية مدعومة بالذكاء الاصطناعي لاكتشاف السكري وإدارة المرضى مع لوحة تحكم شاملة للإدارة وبوابة للأطباء."
  },
  "View All Projects": {
    "en": "View All Projects",
    "ar": "عرض جميع المشاريع"
  },
  "Industries": {
    "en": "Industries",
    "ar": "صناعات"
  },
  "Transforming Businesses Across Industries": {
    "en": "Transforming Businesses Across Industries",
    "ar": "تحويل الأعمال عبر الصناعات"
  },
  "Our expertise spans multiple sectors, delivering tailored solutions that address unique industry challenges and opportunities": {
    "en": "Our expertise spans multiple sectors, delivering tailored solutions that address unique industry challenges and opportunities",
    "ar": "خبرتنا تمتد عبر قطاعات متعددة، نقدم حلولاً مخصصة تعالج التحديات والفرص الفريدة للصناعة"
  },
  "Healthcare": {
    "en": "Healthcare",
    "ar": "الرعاية الصحية"
  },
  "Digital health solutions and patient management systems": {
    "en": "Digital health solutions and patient management systems",
    "ar": "حلول الصحة الرقمية وأنظمة إدارة المرضى"
  },
  "Finance & Banking": {
    "en": "Finance & Banking",
    "ar": "المالية والمصرفية"
  },
  "Secure fintech solutions and banking systems": {
    "en": "Secure fintech solutions and banking systems",
    "ar": "حلول التكنولوجيا المالية الآمنة والأنظمة المصرفية"
  },
  "E-commerce & Retail": {
    "en": "E-commerce & Retail",
    "ar": "التجارة الإلكترونية والتجزئة"
  },
  "Online marketplaces and retail management platforms": {
    "en": "Online marketplaces and retail management platforms",
    "ar": "الأسواق الإلكترونية ومنصات إدارة التجزئة"
  },
  "Education": {
    "en": "Education",
    "ar": "التعليم"
  },
  "E-learning platforms and educational management systems": {
    "en": "E-learning platforms and educational management systems",
    "ar": "منصات التعلم الإلكتروني وأنظمة الإدارة التعليمية"
  },
  "Manufacturing": {
    "en": "Manufacturing",
    "ar": "التصنيع"
  },
  "Industrial automation and production management": {
    "en": "Industrial automation and production management",
    "ar": "الأتمتة الصناعية وإدارة الإنتاج"
  },
  "Real Estate": {
    "en": "Real Estate",
    "ar": "العقارات"
  },
  "Property management and real estate platforms": {
    "en": "Property management and real estate platforms",
    "ar": "إدارة الممتلكات ومنصات العقارات"
  },
  "Logistics & Supply Chain": {
    "en": "Logistics & Supply Chain",
    "ar": "اللوجستيات وسلسلة التوريد"
  },
  "Supply chain optimization and tracking systems": {
    "en": "Supply chain optimization and tracking systems",
    "ar": "تحسين سلسلة التوريد وأنظمة التتبع"
  },
  "Government & Public Sector": {
    "en": "Government & Public Sector",
    "ar": "الحكومة والقطاع العام"
  },
  "Digital government services and citizen platforms": {
    "en": "Digital government services and citizen platforms",
    "ar": "خدمات الحكومة الرقمية ومنصات المواطنين"
  },
  "Our Process": {
    "en": "Our Process",
    "ar": "عمليتنا"
  },
  "How We Bring Your Vision to Life": {
    "en": "How We Bring Your Vision to Life",
    "ar": "كيف نحقق رؤيتك إلى واقع"
  },
  "Our proven methodology ensures successful project delivery from concept to deployment and beyond": {
    "en": "Our proven methodology ensures successful project delivery from concept to deployment and beyond",
    "ar": "منهجيتنا المثبتة تضمن التسليم الناجح للمشروع من المفهوم إلى النشر وما بعده"
  },
  "Discovery & Planning": {
    "en": "Discovery & Planning",
    "ar": "الاستكشاف والتخطيط"
  },
  "Understanding your business needs and defining project scope": {
    "en": "Understanding your business needs and defining project scope",
    "ar": "فهم احتياجات عملك وتحديد نطاق المشروع"
  },
  "Design & Prototyping": {
    "en": "Design & Prototyping",
    "ar": "التصميم والنموذج الأولي"
  },
  "Creating intuitive designs and interactive prototypes": {
    "en": "Creating intuitive designs and interactive prototypes",
    "ar": "إنشاء تصاميم بديهية ونماذج أولية تفاعلية"
  },
  "Development & Testing": {
    "en": "Development & Testing",
    "ar": "التطوير والاختبار"
  },
  "Building robust solutions with rigorous quality assurance": {
    "en": "Building robust solutions with rigorous quality assurance",
    "ar": "بناء حلول قوية مع ضمان الجودة الصارم"
  },
  "Launch & Support": {
    "en": "Launch & Support",
    "ar": "الإطلاق والدعم"
  },
  "Smooth deployment with ongoing maintenance and support": {
    "en": "Smooth deployment with ongoing maintenance and support",
    "ar": "نشر سلس مع الصيانة والدعم المستمر"
  },
  "Testimonials": {
    "en": "Testimonials",
    "ar": "شهادات العملاء"
  },
  "What Our Clients Say": {
    "en": "What Our Clients Say",
    "ar": "ما يقوله عملاؤنا"
  },
  "Trusted by businesses across MENA to deliver exceptional digital solutions": {
    "en": "Trusted by businesses across MENA to deliver exceptional digital solutions",
    "ar": "موثوق بها من قبل الشركات عبر منطقة الشرق الأوسط وشمال أفريقيا لتقديم حلول رقمية استثنائية"
  },
  "Elenta Systems transformed our entire business operations with their custom ERP solution. The bilingual interface and cultural understanding made the transition seamless for our team.": {
    "en": "Elenta Systems transformed our entire business operations with their custom ERP solution. The bilingual interface and cultural understanding made the transition seamless for our team.",
    "ar": "غيرت شركة إلنتا سيستمز عمليات أعمالنا بالكامل بحل تخطيط الموارد المؤسسية المخصص. الواجهة ثنائية اللغة والفهم الثقافي جعل الانتقال سلساً لفريقنا."
  },
  "Ahmed Hassan": {
    "en": "Ahmed Hassan",
    "ar": "أحمد حسن"
  },
  "CEO, TechCorp Egypt": {
    "en": "CEO, TechCorp Egypt",
    "ar": "المدير التنفيذي، تك كورب مصر"
  },
  "Outstanding mobile app development! They created an intuitive e-commerce platform that significantly increased our online sales. Professional, reliable, and always on time.": {
    "en": "Outstanding mobile app development! They created an intuitive e-commerce platform that significantly increased our online sales. Professional, reliable, and always on time.",
    "ar": "تطوير تطبيقات الهاتف المحمول المتميز! أنشأوا منصة تجارة إلكترونية بديهية زادت بشكل كبير من مبيعاتنا عبر الإنترنت. مهنيون وموثوقون ودائماً في الوقت المحدد."
  },
  "Sarah Mohamed": {
    "en": "Sarah Mohamed",
    "ar": "سارة محمد"
  },
  "Founder, Digital Bazaar": {
    "en": "Founder, Digital Bazaar",
    "ar": "المؤسس، البازار الرقمي"
  },
  "Their AI automation solution revolutionized our workflow efficiency. The intelligent reporting dashboard provides insights we never had before. Highly recommend their expertise!": {
    "en": "Their AI automation solution revolutionized our workflow efficiency. The intelligent reporting dashboard provides insights we never had before. Highly recommend their expertise!",
    "ar": "حل الأتمتة بالذكاء الاصطناعي الخاص بهم ثوّر كفاءة سير العمل لدينا. لوحة التحكم الذكية للتقارير توفر رؤى لم نحصل عليها من قبل. أنصح بشدة بخبرتهم!"
  },
  "Khalid Al-Rashid": {
    "en": "Khalid Al-Rashid",
    "ar": "خالد الراشد"
  },
  "CTO, Innovation Hub": {
    "en": "CTO, Innovation Hub",
    "ar": "مدير التكنولوجيا، مركز الابتكار"
  },
  "Why Choose Us": {
    "en": "Why Choose Us",
    "ar": "لماذا تختارنا"
  },
  "Your Trusted Digital Transformation Partner": {
    "en": "Your Trusted Digital Transformation Partner",
    "ar": "شريكك الموثوق للتحول الرقمي"
  },
  "Based in Egypt and serving the MENA region, Elenta Systems combines cutting-edge technology with deep cultural understanding. We deliver solutions that are not just functional, but culturally relevant, user-friendly, and designed to scale with your business growth.": {
    "en": "Based in Egypt and serving the MENA region, Elenta Systems combines cutting-edge technology with deep cultural understanding. We deliver solutions that are not just functional, but culturally relevant, user-friendly, and designed to scale with your business growth.",
    "ar": "تقع شركة إلنتا سيستمز في مصر وتخدم منطقة الشرق الأوسط وشمال أفريقيا، وتجمع بين التكنولوجيا المتطورة والفهم الثقافي العميق. نقدم حلولاً ليست وظيفية فحسب، بل ذات صلة ثقافية وسهلة الاستخدام ومصممة للنمو مع نمو عملك."
  },
  "MENA Regional Expertise": {
    "en": "MENA Regional Expertise",
    "ar": "خبرة إقليمية في الشرق الأوسط وشمال أفريقيا"
  },
  "Deep understanding of local markets, regulations, and cultural nuances": {
    "en": "Deep understanding of local markets, regulations, and cultural nuances",
    "ar": "فهم عميق للأسواق المحلية واللوائح والفروق الثقافية"
  },
  "Bilingual Excellence": {
    "en": "Bilingual Excellence",
    "ar": "التميز ثنائي اللغة"
  },
  "Native Arabic and English support with proper RTL implementation": {
    "en": "Native Arabic and English support with proper RTL implementation",
    "ar": "دعم أصلي للعربية والإنجليزية مع تنفيذ صحيح للنصوص من اليمين إلى اليسار"
  },
  "Future-Ready Technology": {
    "en": "Future-Ready Technology",
    "ar": "تكنولوجيا مستعدة للمستقبل"
  },
  "Modern, scalable solutions built with latest frameworks and best practices": {
    "en": "Modern, scalable solutions built with latest frameworks and best practices",
    "ar": "حلول حديثة وقابلة للتوسع مبنية بأحدث الأطر وأفضل الممارسات"
  },
  "FAQ": {
    "en": "FAQ",
    "ar": "الأسئلة الشائعة"
  },
  "Frequently Asked Questions": {
    "en": "Frequently Asked Questions",
    "ar": "الأسئلة المتكررة"
  },
  "Find answers to common questions about our services and processes": {
    "en": "Find answers to common questions about our services and processes",
    "ar": "اعثر على إجابات للأسئلة الشائعة حول خدماتنا وعملياتنا"
  },
  "What technologies do you specialize in?": {
    "en": "What technologies do you specialize in?",
    "ar": "ما هي التقنيات التي تتخصصون فيها؟"
  },
  "We specialize in .NET and Angular development, advanced AI solutions (LLM, RAG, AI Agents, Chatbots), cloud platforms (AWS, Azure), and enterprise solutions like ERP and CRM systems.": {
    "en": "We specialize in .NET and Angular development, advanced AI solutions (LLM, RAG, AI Agents, Chatbots), cloud platforms (AWS, Azure), and enterprise solutions like ERP and CRM systems.",
    "ar": "نتخصص في تطوير .NET و Angular، وحلول الذكاء الاصطناعي المتقدمة (LLM، RAG، الوكلاء الذكيين، روبوتات الدردشة)، والمنصات السحابية (AWS، Azure)، والحلول المؤسسية مثل أنظمة تخطيط الموارد المؤسسية وإدارة علاقات العملاء."
  },
  "How long does a typical project take?": {
    "en": "How long does a typical project take?",
    "ar": "كم يستغرق المشروع النموذجي؟"
  },
  "Project timelines vary based on complexity and requirements. Simple websites take 2-4 weeks, mobile apps 6-12 weeks, and enterprise solutions 3-6 months. We provide detailed timelines during the planning phase.": {
    "en": "Project timelines vary based on complexity and requirements. Simple websites take 2-4 weeks, mobile apps 6-12 weeks, and enterprise solutions 3-6 months. We provide detailed timelines during the planning phase.",
    "ar": "تختلف الجداول الزمنية للمشاريع حسب التعقيد والمتطلبات. المواقع البسيطة تستغرق 2-4 أسابيع، تطبيقات الهاتف المحمول 6-12 أسبوعاً، والحلول المؤسسية 3-6 أشهر. نقدم جداول زمنية مفصلة خلال مرحلة التخطيط."
  },
  "Do you provide ongoing support and maintenance?": {
    "en": "Do you provide ongoing support and maintenance?",
    "ar": "هل تقدمون الدعم والصيانة المستمرة؟"
  },
  "Yes, we offer comprehensive post-launch support including bug fixes, security updates, performance monitoring, and feature enhancements. We provide different support packages to meet your specific needs.": {
    "en": "Yes, we offer comprehensive post-launch support including bug fixes, security updates, performance monitoring, and feature enhancements. We provide different support packages to meet your specific needs.",
    "ar": "نعم، نقدم دعماً شاملاً بعد الإطلاق يشمل إصلاح الأخطاء وتحديثات الأمان ومراقبة الأداء وتحسين الميزات. نقدم حزم دعم مختلفة لتلبية احتياجاتك المحددة."
  },
  "Can you work with our existing team?": {
    "en": "Can you work with our existing team?",
    "ar": "هل يمكنكم العمل مع فريقنا الحالي؟"
  },
  "Absolutely! We excel at collaborating with existing teams, whether for additional development resources, specialized expertise, or project consultation. We adapt to your workflow and communication preferences.": {
    "en": "Absolutely! We excel at collaborating with existing teams, whether for additional development resources, specialized expertise, or project consultation. We adapt to your workflow and communication preferences.",
    "ar": "بالطبع! نتفوق في التعاون مع الفرق الحالية، سواء للموارد التطويرية الإضافية أو الخبرة المتخصصة أو استشارة المشاريع. نتكيف مع سير عملك وتفضيلات التواصل."
  },
  "What is your pricing model?": {
    "en": "What is your pricing model?",
    "ar": "ما هو نموذج التسعير الخاص بكم؟"
  },
  "We offer flexible pricing models including fixed-price projects, hourly rates for ongoing work, and retainer agreements for long-term partnerships. Pricing is always transparent with detailed breakdowns provided upfront.": {
    "en": "We offer flexible pricing models including fixed-price projects, hourly rates for ongoing work, and retainer agreements for long-term partnerships. Pricing is always transparent with detailed breakdowns provided upfront.",
    "ar": "نقدم نماذج تسعير مرنة بما في ذلك المشاريع بسعر ثابت والأسعار بالساعة للعمل المستمر واتفاقيات الحجز للشراكات طويلة المدى. التسعير شفاف دائماً مع تفاصيل مفصلة مقدمة مسبقاً."
  },
  "Do you work with international clients?": {
    "en": "Do you work with international clients?",
    "ar": "هل تعملون مع العملاء الدوليين؟"
  },
  "Yes, we work with clients globally while specializing in the MENA region. Our bilingual team and understanding of international business practices make us an ideal partner for cross-border projects.": {
    "en": "Yes, we work with clients globally while specializing in the MENA region. Our bilingual team and understanding of international business practices make us an ideal partner for cross-border projects.",
    "ar": "نعم، نعمل مع العملاء عالمياً بينما نتخصص في منطقة الشرق الأوسط وشمال أفريقيا. فريقنا ثنائي اللغة وفهمنا لممارسات الأعمال الدولية يجعلنا شريكاً مثالياً للمشاريع العابرة للحدود."
  },
  "Contact Us": {
    "en": "Contact Us",
    "ar": "تواصل معنا"
  },
  "Get In Touch": {
    "en": "Get In Touch",
    "ar": "تواصل معنا"
  },
  "Ready to transform your ideas into reality? Let's discuss your project and explore how we can help you achieve your digital goals.": {
    "en": "Ready to transform your ideas into reality? Let's discuss your project and explore how we can help you achieve your digital goals.",
    "ar": "هل أنت مستعد لتحويل أفكارك إلى واقع؟ دعنا نناقش مشروعك ونستكشف كيف يمكننا مساعدتك في تحقيق أهدافك الرقمية."
  },
  "Send us a Message": {
    "en": "Send us a Message",
    "ar": "أرسل لنا رسالة"
  },
  "Full Name": {
    "en": "Full Name",
    "ar": "الاسم الكامل"
  },
  "Email Address": {
    "en": "Email Address",
    "ar": "البريد الإلكتروني"
  },
  "Phone Number (Optional)": {
    "en": "Phone Number (Optional)",
    "ar": "رقم الهاتف (اختياري)"
  },
  "Service Interested In": {
    "en": "Service Interested In",
    "ar": "الخدمة المهتم بها"
  },
  "Select a service": {
    "en": "Select a service",
    "ar": "اختر خدمة"
  },
  "Project Details": {
    "en": "Project Details",
    "ar": "تفاصيل المشروع"
  },
  "Send Message": {
    "en": "Send Message",
    "ar": "إرسال الرسالة"
  },
  "Contact Information": {
    "en": "Contact Information",
    "ar": "معلومات الاتصال"
  },
  "We'll respond within 24 hours": {
    "en": "We'll respond within 24 hours",
    "ar": "سنرد في غضون 24 ساعة"
  },
  "Location": {
    "en": "Location",
    "ar": "الموقع"
  },
  "Alexandria, Egypt": {
    "en": "Alexandria, Egypt",
    "ar": "الاسكندرية، مصر"
  },
  "Serving MENA Region": {
    "en": "Serving MENA Region",
    "ar": "نخدم منطقة الشرق الأوسط وشمال أفريقيا"
  },
  "Business Hours": {
    "en": "Business Hours",
    "ar": "ساعات العمل"
  },
  "Sunday - Thursday: 9:00 AM - 6:00 PM (EET)": {
    "en": "Sunday - Thursday: 9:00 AM - 6:00 PM (EET)",
    "ar": "الأحد - الخميس: 9:00 ص - 6:00 م (توقيت القاهرة)"
  },
  "Emergency support available 24/7": {
    "en": "Emergency support available 24/7",
    "ar": "دعم الطوارئ متاح 24/7"
  },
  "Follow Us": {
    "en": "Follow Us",
    "ar": "تابعنا"
  },
  "Professional updates and insights": {
    "en": "Professional updates and insights",
    "ar": "تحديثات مهنية ورؤى"
  },
  "Latest news and community updates": {
    "en": "Latest news and community updates",
    "ar": "آخر الأخبار وتحديثات المجتمع"
  },
  "Quick Response": {
    "en": "Quick Response",
    "ar": "استجابة سريعة"
  },
  "We typically respond to all inquiries within 2-4 hours during business hours": {
    "en": "We typically respond to all inquiries within 2-4 hours during business hours",
    "ar": "نحن عادة نرد على جميع الاستفسارات في غضون 2-4 ساعات خلال ساعات العمل"
  },
  "Empowering businesses across MENA with innovative digital solutions. We transform ideas into interfaces that drive growth and operational excellence.": {
    "en": "Empowering businesses across MENA with innovative digital solutions. We transform ideas into interfaces that drive growth and operational excellence.",
    "ar": "تمكين الشركات عبر منطقة الشرق الأوسط وشمال أفريقيا بحلول رقمية مبتكرة. نحول الأفكار إلى واجهات تحفز النمو والتميز التشغيلي."
  },
  "Quick Links": {
    "en": "Quick Links",
    "ar": "روابط سريعة"
  },
  "Our Services": {
    "en": "Our Services",
    "ar": "خدماتنا"
  },
  "Web & Mobile": {
    "en": "Web & Mobile",
    "ar": "الويب والهاتف"
  },
  "© 2025 Elenta Systems. All rights reserved.": {
    "en": "© 2025 Elenta Systems. All rights reserved.",
    "ar": "© 2025 شركة إلنتا سيستمز. جميع الحقوق محفوظة."
  },
  "Privacy Policy": {
    "en": "Privacy Policy",
    "ar": "سياسة الخصوصية"
  },
  "Terms of Service": {
    "en": "Terms of Service",
    "ar": "شروط الخدمة"
  },
  "Message sent successfully! We'll get back to you soon.": {
    "en": "Message sent successfully! We'll get back to you soon.",
    "ar": "تم إرسال الرسالة بنجاح! سنتواصل معك قريباً."
  },
  "placeholder::Your Name": {
    "en": "Your Name",
    "ar": "اسمك"
  },
  "placeholder::your@email.com": {
    "en": "your@email.com",
    "ar": "your@email.com"
  },
  "placeholder::+20 xxx xxx xxxx": {
    "en": "+20 xxx xxx xxxx",
    "ar": "+20 xxx xxx xxxx"
  },
  "placeholder::Tell us about your project, requirements, and timeline...": {
    "en": "Tell us about your project, requirements, and timeline...",
    "ar": "أخبرنا عن مشروعك ومتطلباتك والجدول الزمني..."
  },
  "Transforming Ideas into Digital Reality": {
    "en": "Transforming Ideas into Digital Reality",
    "ar": "تحويل الأفكار إلى واقع رقمي"
  },
  "Explore our diverse portfolio of successful projects spanning robotics, healthcare, consulting, and beyond": {
    "en": "Explore our diverse portfolio of successful projects spanning robotics, healthcare, consulting, and beyond",
    "ar": "استكشف محفظتنا المتنوعة من المشاريع الناجحة التي تشمل الروبوتات والرعاية الصحية والاستشارات وما بعدها"
  },
  "Major Projects": {
    "en": "Major Projects",
    "ar": "مشاريع رئيسية"
  },
  "Success Rate": {
    "en": "Success Rate",
    "ar": "معدل النجاح"
  },
  "Live Site": {
    "en": "Live Site",
    "ar": "الموقع المباشر"
  },
  "A cutting-edge robotics company website featuring modern design, seamless user experience, and comprehensive showcasing of innovative robotic solutions and autonomous systems.": {
    "en": "A cutting-edge robotics company website featuring modern design, seamless user experience, and comprehensive showcasing of innovative robotic solutions and autonomous systems.",
    "ar": "موقع شركة روبوتات متطور يتميز بتصميم حديث وتجربة مستخدم سلسة وعرض شامل للحلول الروبوتية المبتكرة والأنظمة المستقلة."
  },
  "Key Features": {
    "en": "Key Features",
    "ar": "الميزات الرئيسية"
  },
  "Responsive design optimized for all devices": {
    "en": "Responsive design optimized for all devices",
    "ar": "تصميم متجاوب محسّن لجميع الأجهزة"
  },
  "Interactive product showcase with animations": {
    "en": "Interactive product showcase with animations",
    "ar": "عرض تفاعلي للمنتجات مع الرسوم المتحركة"
  },
  "Advanced contact and inquiry system": {
    "en": "Advanced contact and inquiry system",
    "ar": "نظام متقدم للاتصال والاستفسارات"
  },
  "SEO optimized for maximum visibility": {
    "en": "SEO optimized for maximum visibility",
    "ar": "محسّن لمحركات البحث لأقصى قدر من الرؤية"
  },
  "Technologies Used": {
    "en": "Technologies Used",
    "ar": "التقنيات المستخدمة"
  },
  "Internal Systems": {
    "en": "Internal Systems",
    "ar": "الأنظمة الداخلية"
  },
  "Developed comprehensive internal management systems including admin dashboards for content management, user administration, and analytics tracking.": {
    "en": "Developed comprehensive internal management systems including admin dashboards for content management, user administration, and analytics tracking.",
    "ar": "تم تطوير أنظمة إدارة داخلية شاملة تشمل لوحات تحكم الإدارة لإدارة المحتوى وإدارة المستخدمين وتتبع التحليلات."
  },
  "A comprehensive consulting platform designed to connect businesses with expert consultants, streamline the consultation process, and provide robust project management tools for the consulting industry.": {
    "en": "A comprehensive consulting platform designed to connect businesses with expert consultants, streamline the consultation process, and provide robust project management tools for the consulting industry.",
    "ar": "منصة استشارية شاملة مصممة لربط الشركات بالخبراء الاستشاريين وتبسيط عملية الاستشارة وتوفير أدوات إدارة مشاريع قوية لصناعة الاستشارات."
  },
  "Platform Features": {
    "en": "Platform Features",
    "ar": "ميزات المنصة"
  },
  "Expert consultant matching system": {
    "en": "Expert consultant matching system",
    "ar": "نظام مطابقة الخبراء الاستشاريين"
  },
  "Real-time project tracking and management": {
    "en": "Real-time project tracking and management",
    "ar": "تتبع وإدارة المشاريع في الوقت الفعلي"
  },
  "Secure communication channels": {
    "en": "Secure communication channels",
    "ar": "قنوات اتصال آمنة"
  },
  "Integrated billing and payment system": {
    "en": "Integrated billing and payment system",
    "ar": "نظام متكامل للفوترة والدفع"
  },
  "Advanced analytics and reporting": {
    "en": "Advanced analytics and reporting",
    "ar": "تحليلات وتقارير متقدمة"
  },
  "Technology Stack": {
    "en": "Technology Stack",
    "ar": "مجموعة التقنيات"
  },
  "Target Industries": {
    "en": "Target Industries",
    "ar": "الصناعات المستهدفة"
  },
  "Management Consulting": {
    "en": "Management Consulting",
    "ar": "الاستشارات الإدارية"
  },
  "Technology Consulting": {
    "en": "Technology Consulting",
    "ar": "الاستشارات التقنية"
  },
  "Financial Advisory": {
    "en": "Financial Advisory",
    "ar": "الاستشارات المالية"
  },
  "Business Strategy": {
    "en": "Business Strategy",
    "ar": "استراتيجية الأعمال"
  },
  "Project Impact": {
    "en": "Project Impact",
    "ar": "تأثير المشروع"
  },
  "Successfully streamlined consultation processes for 50+ businesses, resulting in 40% improved efficiency and enhanced client satisfaction rates.": {
    "en": "Successfully streamlined consultation processes for 50+ businesses, resulting in 40% improved efficiency and enhanced client satisfaction rates.",
    "ar": "نجح في تبسيط عمليات الاستشارة لأكثر من 50 شركة، مما أدى إلى تحسين الكفاءة بنسبة 40% وتعزيز معدلات رضا العملاء."
  },
  "Internal System": {
    "en": "Internal System",
    "ar": "نظام داخلي"
  },
  "An advanced AI-powered medical platform designed for diabetic detection and comprehensive patient management. This internal system serves healthcare providers with cutting-edge diagnostic tools and streamlined patient care workflows.": {
    "en": "An advanced AI-powered medical platform designed for diabetic detection and comprehensive patient management. This internal system serves healthcare providers with cutting-edge diagnostic tools and streamlined patient care workflows.",
    "ar": "منصة طبية متقدمة مدعومة بالذكاء الاصطناعي مصممة لاكتشاف السكري وإدارة المرضى الشاملة. يخدم هذا النظام الداخلي مقدمي الرعاية الصحية بأدوات تشخيص متطورة وسير عمل مبسط لرعاية المرضى."
  },
  "AI Capabilities": {
    "en": "AI Capabilities",
    "ar": "قدرات الذكاء الاصطناعي"
  },
  "Advanced diabetic detection algorithms": {
    "en": "Advanced diabetic detection algorithms",
    "ar": "خوارزميات متقدمة لاكتشاف السكري"
  },
  "Machine learning predictive analytics": {
    "en": "Machine learning predictive analytics",
    "ar": "تحليلات تنبؤية بالتعلم الآلي"
  },
  "Real-time risk assessment and monitoring": {
    "en": "Real-time risk assessment and monitoring",
    "ar": "تقييم ومراقبة المخاطر في الوقت الفعلي"
  },
  "Intelligent treatment recommendations": {
    "en": "Intelligent treatment recommendations",
    "ar": "توصيات علاج ذكية"
  },
  "System Modules": {
    "en": "System Modules",
    "ar": "وحدات النظام"
  },
  "Admin Dashboard": {
    "en": "Admin Dashboard",
    "ar": "لوحة تحكم الإدارة"
  },
  "Comprehensive system management and user administration": {
    "en": "Comprehensive system management and user administration",
    "ar": "إدارة شاملة للنظام وإدارة المستخدمين"
  },
  "Doctor Portal": {
    "en": "Doctor Portal",
    "ar": "بوابة الأطباء"
  },
  "Clinical tools and patient management interface": {
    "en": "Clinical tools and patient management interface",
    "ar": "أدوات سريرية وواجهة إدارة المرضى"
  },
  "Patient Management": {
    "en": "Patient Management",
    "ar": "إدارة المرضى"
  },
  "Secure patient records and treatment tracking": {
    "en": "Secure patient records and treatment tracking",
    "ar": "سجلات المرضى الآمنة وتتبع العلاج"
  },
  "Blog & Resources": {
    "en": "Blog & Resources",
    "ar": "المدونة والموارد"
  },
  "Medical content management and patient education": {
    "en": "Medical content management and patient education",
    "ar": "إدارة المحتوى الطبي وتعليم المرضى"
  },
  "Platform Screenshots": {
    "en": "Platform Screenshots",
    "ar": "لقطات شاشة المنصة"
  },
  "More screenshots available": {
    "en": "More screenshots available",
    "ar": "المزيد من لقطات الشاشة متاحة"
  },
  "Ready to Start Your Next Project?": {
    "en": "Ready to Start Your Next Project?",
    "ar": "مستعد لبدء مشروعك التالي؟"
  },
  "Let's discuss how we can help transform your ideas into innovative digital solutions": {
    "en": "Let's discuss how we can help transform your ideas into innovative digital solutions",
    "ar": "دعنا نناقش كيف يمكننا مساعدتك في تحويل أفكارك إلى حلول رقمية مبتكرة"
  },
  "Transforming businesses across MENA with innovative digital solutions, cutting-edge technology, and cultural understanding.": {
    "en": "Transforming businesses across MENA with innovative digital solutions, cutting-edge technology, and cultural understanding.",
    "ar": "تحويل الأعمال عبر منطقة الشرق الأوسط وشمال أفريقيا بحلول رقمية مبتكرة وتكنولوجيا متطورة وفهم ثقافي."
  },
  "Portfolio": {
    "en": "Portfolio",
    "ar": "أعمالنا"
  },
  "About Us": {
    "en": "About Us",
    "ar": "عن الشركة"
  },
  "Contact Info": {
    "en": "Contact Info",
    "ar": "معلومات الاتصال"
  },
  "Sun-Thu: 9AM-6PM": {
    "en": "Sun-Thu: 9AM-6PM",
    "ar": "الأحد-الخميس: 9ص-6م"
  },
  "Your privacy is important to us. Learn how we protect and handle your information.": {
    "en": "Your privacy is important to us. Learn how we protect and handle your information.",
    "ar": "خصوصيتك مهمة بالنسبة لنا. تعرف على كيفية حماية ومعالجة معلوماتك."
  },
  "Last updated: January 2025": {
    "en": "Last updated: January 2025",
    "ar": "آخر تحديث: يناير 2025"
  },
  "Introduction": {
    "en": "Introduction",
    "ar": "مقدمة"
  },
  "At Elenta Systems ('we', 'our', or 'us'), we are committed to protecting your privacy and personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our services.": {
    "en": "At Elenta Systems ('we', 'our', or 'us'), we are committed to protecting your privacy and personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our services.",
    "ar": "في شركة إلنتا سيستمز ('نحن' أو 'لنا')، نحن ملتزمون بحماية خصوصيتك ومعلوماتك الشخصية. تشرح سياسة الخصوصية هذه كيفية جمع واستخدام والكشف عن وحماية معلوماتك عند زيارة موقعنا أو استخدام خدماتنا."
  },
  "Information We Collect": {
    "en": "Information We Collect",
    "ar": "المعلومات التي نجمعها"
  },
  "Personal Information": {
    "en": "Personal Information",
    "ar": "المعلومات الشخصية"
  },
  "We may collect personal information that you voluntarily provide to us, including:": {
    "en": "We may collect personal information that you voluntarily provide to us, including:",
    "ar": "قد نجمع المعلومات الشخصية التي تقدمها لنا طوعاً، بما في ذلك:"
  },
  "Name and contact information": {
    "en": "Name and contact information",
    "ar": "الاسم ومعلومات الاتصال"
  },
  "Email address and phone number": {
    "en": "Email address and phone number",
    "ar": "عنوان البريد الإلكتروني ورقم الهاتف"
  },
  "Company information and job title": {
    "en": "Company information and job title",
    "ar": "معلومات الشركة والمسمى الوظيفي"
  },
  "Project requirements and specifications": {
    "en": "Project requirements and specifications",
    "ar": "متطلبات ومواصفات المشروع"
  },
  "Communication preferences": {
    "en": "Communication preferences",
    "ar": "تفضيلات التواصل"
  },
  "Automatically Collected Information": {
    "en": "Automatically Collected Information",
    "ar": "المعلومات المجمعة تلقائياً"
  },
  "When you visit our website, we may automatically collect certain information about your device and usage patterns:": {
    "en": "When you visit our website, we may automatically collect certain information about your device and usage patterns:",
    "ar": "عند زيارة موقعنا، قد نجمع تلقائياً معلومات معينة حول جهازك وأنماط الاستخدام:"
  },
  "IP address and browser information": {
    "en": "IP address and browser information",
    "ar": "عنوان IP ومعلومات المتصفح"
  },
  "Pages visited and time spent on our website": {
    "en": "Pages visited and time spent on our website",
    "ar": "الصفحات المزارة والوقت المقضي على موقعنا"
  },
  "Referring website and search terms": {
    "en": "Referring website and search terms",
    "ar": "الموقع المرجعي ومصطلحات البحث"
  },
  "Device type and operating system": {
    "en": "Device type and operating system",
    "ar": "نوع الجهاز ونظام التشغيل"
  },
  "How We Use Your Information": {
    "en": "How We Use Your Information",
    "ar": "كيف نستخدم معلوماتك"
  },
  "We use the information we collect for various purposes, including:": {
    "en": "We use the information we collect for various purposes, including:",
    "ar": "نستخدم المعلومات التي نجمعها لأغراض مختلفة، بما في ذلك:"
  },
  "Providing and maintaining our services": {
    "en": "Providing and maintaining our services",
    "ar": "تقديم وصيانة خدماتنا"
  },
  "Responding to your inquiries and requests": {
    "en": "Responding to your inquiries and requests",
    "ar": "الرد على استفساراتك وطلباتك"
  },
  "Communicating with you about our services": {
    "en": "Communicating with you about our services",
    "ar": "التواصل معك حول خدماتنا"
  },
  "Improving our website and services": {
    "en": "Improving our website and services",
    "ar": "تحسين موقعنا وخدماتنا"
  },
  "Sending newsletters and marketing communications (with your consent)": {
    "en": "Sending newsletters and marketing communications (with your consent)",
    "ar": "إرسال النشرات الإخبارية والتواصل التسويقي (بموافقتك)"
  },
  "Complying with legal obligations": {
    "en": "Complying with legal obligations",
    "ar": "الامتثال للالتزامات القانونية"
  },
  "Information Sharing and Disclosure": {
    "en": "Information Sharing and Disclosure",
    "ar": "مشاركة المعلومات والكشف عنها"
  },
  "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except in the following circumstances:": {
    "en": "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except in the following circumstances:",
    "ar": "نحن لا نبيع أو نتاجر أو ننقل معلوماتك الشخصية إلى أطراف ثالثة دون موافقتك، إلا في الظروف التالية:"
  },
  "Service providers who assist us in operating our website and conducting our business": {
    "en": "Service providers who assist us in operating our website and conducting our business",
    "ar": "مقدمي الخدمات الذين يساعدوننا في تشغيل موقعنا وإدارة أعمالنا"
  },
  "When required by law or to protect our rights and safety": {
    "en": "When required by law or to protect our rights and safety",
    "ar": "عندما يتطلب القانون ذلك أو لحماية حقوقنا وسلامتنا"
  },
  "With your explicit consent for specific purposes": {
    "en": "With your explicit consent for specific purposes",
    "ar": "بموافقتك الصريحة لأغراض محددة"
  },
  "Data Security": {
    "en": "Data Security",
    "ar": "أمان البيانات"
  },
  "We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. These measures include:": {
    "en": "We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. These measures include:",
    "ar": "نحن نطبق تدابير أمنية تقنية وتنظيمية مناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التغيير أو الكشف أو التدمير. تشمل هذه التدابير:"
  },
  "Encryption of data in transit and at rest": {
    "en": "Encryption of data in transit and at rest",
    "ar": "تشفير البيانات أثناء النقل والتخزين"
  },
  "Regular security assessments and updates": {
    "en": "Regular security assessments and updates",
    "ar": "تقييمات وتحديثات أمنية منتظمة"
  },
  "Access controls and employee training": {
    "en": "Access controls and employee training",
    "ar": "ضوابط الوصول وتدريب الموظفين"
  },
  "Secure hosting and backup procedures": {
    "en": "Secure hosting and backup procedures",
    "ar": "إجراءات الاستضافة الآمنة والنسخ الاحتياطي"
  },
  "Your Rights and Choices": {
    "en": "Your Rights and Choices",
    "ar": "حقوقك واختياراتك"
  },
  "You have certain rights regarding your personal information, including:": {
    "en": "You have certain rights regarding your personal information, including:",
    "ar": "لديك حقوق معينة فيما يتعلق بمعلوماتك الشخصية، بما في ذلك:"
  },
  "Access: Request access to your personal information": {
    "en": "Access: Request access to your personal information",
    "ar": "الوصول: طلب الوصول إلى معلوماتك الشخصية"
  },
  "Correction: Request correction of inaccurate information": {
    "en": "Correction: Request correction of inaccurate information",
    "ar": "التصحيح: طلب تصحيح المعلومات غير الدقيقة"
  },
  "Deletion: Request deletion of your personal information": {
    "en": "Deletion: Request deletion of your personal information",
    "ar": "الحذف: طلب حذف معلوماتك الشخصية"
  },
  "Portability: Request transfer of your information": {
    "en": "Portability: Request transfer of your information",
    "ar": "النقل: طلب نقل معلوماتك"
  },
  "Opt-out: Unsubscribe from marketing communications": {
    "en": "Opt-out: Unsubscribe from marketing communications",
    "ar": "إلغاء الاشتراك: إلغاء الاشتراك من التواصل التسويقي"
  },
  "To exercise these rights, please contact us using the information provided in the Contact section below.": {
    "en": "To exercise these rights, please contact us using the information provided in the Contact section below.",
    "ar": "لممارسة هذه الحقوق، يرجى التواصل معنا باستخدام المعلومات المقدمة في قسم التواصل أدناه."
  },
  "Cookies and Tracking Technologies": {
    "en": "Cookies and Tracking Technologies",
    "ar": "ملفات تعريف الارتباط وتقنيات التتبع"
  },
  "We use cookies and similar tracking technologies to enhance your browsing experience and analyze website traffic. You can control cookie settings through your browser preferences.": {
    "en": "We use cookies and similar tracking technologies to enhance your browsing experience and analyze website traffic. You can control cookie settings through your browser preferences.",
    "ar": "نحن نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لتحسين تجربة التصفح وتحليل حركة المرور على الموقع. يمكنك التحكم في إعدادات ملفات تعريف الارتباط من خلال تفضيلات المتصفح."
  },
  "International Data Transfers": {
    "en": "International Data Transfers",
    "ar": "نقل البيانات الدولية"
  },
  "Your information may be transferred to and processed in countries other than your country of residence. We ensure that any international transfers comply with applicable data protection laws and include appropriate safeguards.": {
    "en": "Your information may be transferred to and processed in countries other than your country of residence. We ensure that any international transfers comply with applicable data protection laws and include appropriate safeguards.",
    "ar": "قد يتم نقل ومعالجة معلوماتك في بلدان غير بلد إقامتك. نحن نضمن أن أي نقل دولي يتوافق مع قوانين حماية البيانات المعمول بها ويتضمن الضمانات المناسبة."
  },
  "Changes to This Privacy Policy": {
    "en": "Changes to This Privacy Policy",
    "ar": "التغييرات على سياسة الخصوصية"
  },
  "We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page and updating the 'Last updated' date. We encourage you to review this Privacy Policy periodically.": {
    "en": "We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page and updating the 'Last updated' date. We encourage you to review this Privacy Policy periodically.",
    "ar": "قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. سنخطرك بأي تغييرات جوهرية عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة وتحديث تاريخ 'آخر تحديث'. نشجعك على مراجعة سياسة الخصوصية هذه بشكل دوري."
  },
  "If you have any questions about this Privacy Policy or our data practices, please contact us:": {
    "en": "If you have any questions about this Privacy Policy or our data practices, please contact us:",
    "ar": "إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه أو ممارسات البيانات الخاصة بنا، يرجى التواصل معنا:"
  },
  "Email:": {
    "en": "Email:",
    "ar": "البريد الإلكتروني:"
  },
  "Address:": {
    "en": "Address:",
    "ar": "العنوان:"
  },
  "These terms govern your use of our services and establish our mutual responsibilities.": {
    "en": "These terms govern your use of our services and establish our mutual responsibilities.",
    "ar": "تحكم هذه الشروط استخدامك لخدماتنا وتحدد مسؤولياتنا المتبادلة."
  },
  "Acceptance of Terms": {
    "en": "Acceptance of Terms",
    "ar": "قبول الشروط"
  },
  "By accessing or using Elenta Systems' services, you agree to be bound by these Terms of Service ('Terms'). If you disagree with any part of these terms, you may not use our services.": {
    "en": "By accessing or using Elenta Systems' services, you agree to be bound by these Terms of Service ('Terms'). If you disagree with any part of these terms, you may not use our services.",
    "ar": "من خلال الوصول إلى أو استخدام خدمات شركة إلنتا سيستمز، فإنك توافق على الالتزام بشروط الخدمة هذه ('الشروط'). إذا كنت لا توافق على أي جزء من هذه الشروط، فلا يجوز لك استخدام خدماتنا."
  },
  "Description of Services": {
    "en": "Description of Services",
    "ar": "وصف الخدمات"
  },
  "Elenta Systems provides digital transformation services including but not limited to:": {
    "en": "Elenta Systems provides digital transformation services including but not limited to:",
    "ar": "تقدم شركة إلنتا سيستمز خدمات التحول الرقمي بما في ذلك على سبيل المثال لا الحصر:"
  },
  "Enterprise software development and solutions": {
    "en": "Enterprise software development and solutions",
    "ar": "تطوير وحلول البرمجيات المؤسسية"
  },
  "Artificial intelligence and automation services": {
    "en": "Artificial intelligence and automation services",
    "ar": "خدمات الذكاء الاصطناعي والأتمتة"
  },
  "Web and mobile application development": {
    "en": "Web and mobile application development",
    "ar": "تطوير تطبيقات الويب والهاتف المحمول"
  },
  "Cloud computing and infrastructure services": {
    "en": "Cloud computing and infrastructure services",
    "ar": "خدمات الحوسبة السحابية والبنية التحتية"
  },
  "UX/UI design and consulting": {
    "en": "UX/UI design and consulting",
    "ar": "تصميم تجربة المستخدم والاستشارات"
  },
  "Digital transformation consulting": {
    "en": "Digital transformation consulting",
    "ar": "استشارات التحول الرقمي"
  },
  "User Responsibilities": {
    "en": "User Responsibilities",
    "ar": "مسؤوليات المستخدم"
  },
  "When using our services, you agree to:": {
    "en": "When using our services, you agree to:",
    "ar": "عند استخدام خدماتنا، فإنك توافق على:"
  },
  "Provide accurate and complete information": {
    "en": "Provide accurate and complete information",
    "ar": "تقديم معلومات دقيقة وكاملة"
  },
  "Use our services for lawful purposes only": {
    "en": "Use our services for lawful purposes only",
    "ar": "استخدام خدماتنا للأغراض القانونية فقط"
  },
  "Respect intellectual property rights": {
    "en": "Respect intellectual property rights",
    "ar": "احترام حقوق الملكية الفكرية"
  },
  "Maintain the confidentiality of your account credentials": {
    "en": "Maintain the confidentiality of your account credentials",
    "ar": "الحفاظ على سرية بيانات اعتماد حسابك"
  },
  "Comply with all applicable laws and regulations": {
    "en": "Comply with all applicable laws and regulations",
    "ar": "الامتثال لجميع القوانين واللوائح المعمول بها"
  },
  "Not attempt to gain unauthorized access to our systems": {
    "en": "Not attempt to gain unauthorized access to our systems",
    "ar": "عدم محاولة الحصول على وصول غير مصرح به إلى أنظمتنا"
  },
  "Payment Terms": {
    "en": "Payment Terms",
    "ar": "شروط الدفع"
  },
  "Fees and Billing": {
    "en": "Fees and Billing",
    "ar": "الرسوم والفوترة"
  },
  "Payment terms will be specified in individual service agreements. Generally:": {
    "en": "Payment terms will be specified in individual service agreements. Generally:",
    "ar": "سيتم تحديد شروط الدفع في اتفاقيات الخدمة الفردية. بشكل عام:"
  },
  "Invoices are due within 30 days of receipt unless otherwise specified": {
    "en": "Invoices are due within 30 days of receipt unless otherwise specified",
    "ar": "الفواتير مستحقة خلال 30 يوماً من الاستلام ما لم ينص على خلاف ذلك"
  },
  "Late payments may incur additional charges": {
    "en": "Late payments may incur additional charges",
    "ar": "قد تتكبد المدفوعات المتأخرة رسوماً إضافية"
  },
  "All fees are non-refundable unless explicitly stated": {
    "en": "All fees are non-refundable unless explicitly stated",
    "ar": "جميع الرسوم غير قابلة للاسترداد ما لم ينص صراحة على خلاف ذلك"
  },
  "Prices may be subject to change with 30 days' notice": {
    "en": "Prices may be subject to change with 30 days' notice",
    "ar": "قد تخضع الأسعار للتغيير بإشعار 30 يوماً"
  },
  "Suspension for Non-Payment": {
    "en": "Suspension for Non-Payment",
    "ar": "التعليق لعدم الدفع"
  },
  "We reserve the right to suspend or terminate services for accounts with overdue payments. We will provide reasonable notice before taking such action.": {
    "en": "We reserve the right to suspend or terminate services for accounts with overdue payments. We will provide reasonable notice before taking such action.",
    "ar": "نحتفظ بالحق في تعليق أو إنهاء الخدمات للحسابات التي بها مدفوعات متأخرة. سنقدم إشعاراً معقولاً قبل اتخاذ مثل هذا الإجراء."
  },
  "Intellectual Property Rights": {
    "en": "Intellectual Property Rights",
    "ar": "حقوق الملكية الفكرية"
  },
  "Our Intellectual Property": {
    "en": "Our Intellectual Property",
    "ar": "ملكيتنا الفكرية"
  },
  "All content, software, designs, and materials developed by Elenta Systems remain our intellectual property unless explicitly transferred to you in writing.": {
    "en": "All content, software, designs, and materials developed by Elenta Systems remain our intellectual property unless explicitly transferred to you in writing.",
    "ar": "جميع المحتوى والبرامج والتصاميم والمواد التي طورتها شركة إلنتا سيستمز تبقى ملكيتنا الفكرية ما لم يتم نقلها إليك صراحة كتابياً."
  },
  "Client Intellectual Property": {
    "en": "Client Intellectual Property",
    "ar": "الملكية الفكرية للعميل"
  },
  "You retain ownership of your pre-existing intellectual property. You grant us a license to use your materials as necessary to provide our services.": {
    "en": "You retain ownership of your pre-existing intellectual property. You grant us a license to use your materials as necessary to provide our services.",
    "ar": "تحتفظ بملكية ملكيتك الفكرية الموجودة مسبقاً. تمنحنا ترخيصاً لاستخدام موادك حسب الضرورة لتقديم خدماتنا."
  },
  "Work Product Ownership": {
    "en": "Work Product Ownership",
    "ar": "ملكية منتج العمل"
  },
  "Ownership of custom work products will be specified in individual project agreements. Generally, you will own custom developments upon full payment, while we retain rights to general methodologies and frameworks.": {
    "en": "Ownership of custom work products will be specified in individual project agreements. Generally, you will own custom developments upon full payment, while we retain rights to general methodologies and frameworks.",
    "ar": "سيتم تحديد ملكية منتجات العمل المخصصة في اتفاقيات المشاريع الفردية. بشكل عام، ستمتلك التطويرات المخصصة عند الدفع الكامل، بينما نحتفظ بحقوق المنهجيات والأطر العامة."
  },
  "Confidentiality": {
    "en": "Confidentiality",
    "ar": "السرية"
  },
  "We understand the sensitive nature of business information and commit to:": {
    "en": "We understand the sensitive nature of business information and commit to:",
    "ar": "نحن ندرك الطبيعة الحساسة لمعلومات الأعمال ونلتزم بـ:"
  },
  "Maintaining strict confidentiality of all client information": {
    "en": "Maintaining strict confidentiality of all client information",
    "ar": "الحفاظ على السرية الصارمة لجميع معلومات العميل"
  },
  "Using confidential information solely for providing agreed services": {
    "en": "Using confidential information solely for providing agreed services",
    "ar": "استخدام المعلومات السرية فقط لتقديم الخدمات المتفق عليها"
  },
  "Implementing appropriate security measures to protect data": {
    "en": "Implementing appropriate security measures to protect data",
    "ar": "تنفيذ تدابير أمنية مناسبة لحماية البيانات"
  },
  "Not disclosing information to third parties without consent": {
    "en": "Not disclosing information to third parties without consent",
    "ar": "عدم الكشف عن المعلومات لأطراف ثالثة دون موافقة"
  },
  "Limitation of Liability": {
    "en": "Limitation of Liability",
    "ar": "تقييد المسؤولية"
  },
  "To the maximum extent permitted by law:": {
    "en": "To the maximum extent permitted by law:",
    "ar": "إلى أقصى حد يسمح به القانون:"
  },
  "Our total liability shall not exceed the fees paid for the specific service": {
    "en": "Our total liability shall not exceed the fees paid for the specific service",
    "ar": "لن تتجاوز مسؤوليتنا الإجمالية الرسوم المدفوعة للخدمة المحددة"
  },
  "We are not liable for indirect, incidental, or consequential damages": {
    "en": "We are not liable for indirect, incidental, or consequential damages",
    "ar": "نحن غير مسؤولين عن الأضرار غير المباشرة أو العرضية أو التبعية"
  },
  "Force majeure events are excluded from our liability": {
    "en": "Force majeure events are excluded from our liability",
    "ar": "أحداث القوة القاهرة مستثناة من مسؤوليتنا"
  },
  "You are responsible for maintaining backups of your data": {
    "en": "You are responsible for maintaining backups of your data",
    "ar": "أنت مسؤول عن الاحتفاظ بنسخ احتياطية من بياناتك"
  },
  "Service Level Agreements": {
    "en": "Service Level Agreements",
    "ar": "اتفاقيات مستوى الخدمة"
  },
  "We strive to provide reliable services and typically offer:": {
    "en": "We strive to provide reliable services and typically offer:",
    "ar": "نسعى لتقديم خدمات موثوقة ونقدم عادة:"
  },
  "99.9% uptime for hosted solutions (excluding scheduled maintenance)": {
    "en": "99.9% uptime for hosted solutions (excluding scheduled maintenance)",
    "ar": "99.9% وقت تشغيل للحلول المستضافة (باستثناء الصيانة المجدولة)"
  },
  "24-hour response time for critical issues": {
    "en": "24-hour response time for critical issues",
    "ar": "وقت استجابة 24 ساعة للمشاكل الحرجة"
  },
  "Business hours support (Sunday-Thursday, 9 AM - 6 PM EET)": {
    "en": "Business hours support (Sunday-Thursday, 9 AM - 6 PM EET)",
    "ar": "دعم ساعات العمل (الأحد-الخميس، 9 ص - 6 م توقيت القاهرة)"
  },
  "Regular backups and disaster recovery procedures": {
    "en": "Regular backups and disaster recovery procedures",
    "ar": "نسخ احتياطية منتظمة وإجراءات استعادة الكوارث"
  },
  "Termination": {
    "en": "Termination",
    "ar": "الإنهاء"
  },
  "Termination by Either Party": {
    "en": "Termination by Either Party",
    "ar": "الإنهاء من قبل أي من الطرفين"
  },
  "Either party may terminate ongoing services with 30 days' written notice. Project-based work will be completed according to the agreed timeline unless otherwise terminated.": {
    "en": "Either party may terminate ongoing services with 30 days' written notice. Project-based work will be completed according to the agreed timeline unless otherwise terminated.",
    "ar": "يجوز لأي من الطرفين إنهاء الخدمات الجارية بإشعار كتابي لمدة 30 يوماً. سيتم إكمال العمل القائم على المشاريع وفقاً للجدول الزمني المتفق عليه ما لم يتم إنهاؤه بطريقة أخرى."
  },
  "Immediate Termination": {
    "en": "Immediate Termination",
    "ar": "الإنهاء الفوري"
  },
  "We may immediately terminate services if you:": {
    "en": "We may immediately terminate services if you:",
    "ar": "يجوز لنا إنهاء الخدمات فوراً إذا كنت:"
  },
  "Breach these Terms of Service": {
    "en": "Breach these Terms of Service",
    "ar": "تنتهك شروط الخدمة هذه"
  },
  "Fail to pay invoices after receiving notice": {
    "en": "Fail to pay invoices after receiving notice",
    "ar": "تفشل في دفع الفواتير بعد تلقي الإشعار"
  },
  "Use our services for illegal activities": {
    "en": "Use our services for illegal activities",
    "ar": "تستخدم خدماتنا لأنشطة غير قانونية"
  },
  "Attempt to damage our systems or reputation": {
    "en": "Attempt to damage our systems or reputation",
    "ar": "تحاول إلحاق الضرر بأنظمتنا أو سمعتنا"
  },
  "Governing Law and Dispute Resolution": {
    "en": "Governing Law and Dispute Resolution",
    "ar": "القانون الحاكم وحل النزاعات"
  },
  "These Terms are governed by the laws of Egypt. Any disputes arising from these Terms or our services will be resolved through:": {
    "en": "These Terms are governed by the laws of Egypt. Any disputes arising from these Terms or our services will be resolved through:",
    "ar": "تحكم هذه الشروط قوانين مصر. سيتم حل أي نزاعات ناشئة عن هذه الشروط أو خدماتنا من خلال:"
  },
  "Good faith negotiations between the parties": {
    "en": "Good faith negotiations between the parties",
    "ar": "مفاوضات بحسن نية بين الأطراف"
  },
  "Mediation by a mutually agreed mediator": {
    "en": "Mediation by a mutually agreed mediator",
    "ar": "الوساطة من قبل وسيط متفق عليه بشكل متبادل"
  },
  "Arbitration in Cairo, Egypt, if mediation fails": {
    "en": "Arbitration in Cairo, Egypt, if mediation fails",
    "ar": "التحكيم في القاهرة، مصر، إذا فشلت الوساطة"
  },
  "Changes to These Terms": {
    "en": "Changes to These Terms",
    "ar": "التغييرات على هذه الشروط"
  },
  "We may update these Terms from time to time. We will notify you of material changes by email or through our website. Continued use of our services after changes constitutes acceptance of the updated Terms.": {
    "en": "We may update these Terms from time to time. We will notify you of material changes by email or through our website. Continued use of our services after changes constitutes acceptance of the updated Terms.",
    "ar": "قد نقوم بتحديث هذه الشروط من وقت لآخر. سنخطرك بالتغييرات الجوهرية عبر البريد الإلكتروني أو من خلال موقعنا. الاستمرار في استخدام خدماتنا بعد التغييرات يشكل قبولاً للشروط المحدثة."
  },
  "If you have any questions about these Terms of Service, please contact us:": {
    "en": "If you have any questions about these Terms of Service, please contact us:",
    "ar": "إذا كان لديك أي أسئلة حول شروط الخدمة هذه، يرجى التواصل معنا:"
  },
  "Company:": {
    "en": "Company:",
    "ar": "الشركة:"
  },
  "Elenta Systems": {
    "en": "Elenta Systems",
    "ar": "شركة إلنتا سيستمز"
  },
  "Cairo, Egypt": {
    "en": "Cairo, Egypt",
    "ar": "القاهرة، مصر"
  }
} as const;
